# Generated by Django 3.2.12 on 2022-05-29 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20220517_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='act',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 11, 4, 50, 757725)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='amz40z46ktvpfy04', max_length=100),
        ),
    ]
