# Generated by Django 3.2.12 on 2022-05-31 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20220529_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 17, 8, 1, 762386)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='rj4m0wtf6gy4eb47', max_length=100),
        ),
    ]
