# Generated by Django 3.2.12 on 2022-06-08 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20220531_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='market',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smsverified',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 20, 26, 43, 168693)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='otp',
            field=models.CharField(default='7tb42105k2pjdv66', max_length=100),
        ),
    ]
